Token: ""
ChannelId:
  WelcomeMessageChannel: 0
  WelcomeChannel: 0
  RoleBotChannel: 0
RoleId:
  MemberRole: 0
RoleBotRoleId:
  "1": 0
  "2": 0
  "3": 0
  "4": 0
  "5": 0
  "6": 0
  "7": 0
  "8": 0
  "9": 0